package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
	"testing"
)

func TestExportedName(t *testing.T) {
	tests := []struct {
		prop string
		want string
	}{
		{"uri", "URI"},
		{"languageId", "LanguageID"},
		{"textDocument", "TextDocument"},
		{"startCharacter", "StartCharacter"},
		{"hierarchicalDocumentSymbolSupport", "HierarchicalDocumentSymbolSupport"},
		{"includeDeclaration", "IncludeDeclaration"},
		{"containerName", "ContainerName"},
		{"newText", "NewText"},
		{"relatedInformation", "RelatedInformation"},
		{"query", "Query"},
		{"kind", "Kind"},
		{"targetUri", "TargetURI"},
	}
	for _, tt := range tests {
		t.Run(tt.prop, func(t *testing.T) {
			if got := exportedName(tt.prop); got != tt.want {
				t.Errorf("exportedName(%q) = %q, want %q", tt.prop, got, tt.want)
			}
		})
	}
}

func TestSplitCamelWords(t *testing.T) {
	tests := []struct {
		in   string
		want []string
	}{
		{"uri", []string{"uri"}},
		{"languageId", []string{"language", "Id"}},
		{"hierarchicalDocumentSymbolSupport", []string{"hierarchical", "Document", "Symbol", "Support"}},
	}
	for _, tt := range tests {
		got := splitCamelWords(tt.in)
		if len(got) != len(tt.want) {
			t.Fatalf("splitCamelWords(%q) = %v, want %v", tt.in, got, tt.want)
		}
		for i := range got {
			if got[i] != tt.want[i] {
				t.Errorf("splitCamelWords(%q)[%d] = %q, want %q", tt.in, i, got[i], tt.want[i])
			}
		}
	}
}

// TestEmbeddedMetaModelSHA256 pins the vendored metaModel.json; if this ever
// fails it means the file was edited without updating the pin (in main.go)
// — see the same check main() performs at runtime.
func TestEmbeddedMetaModelSHA256(t *testing.T) {
	sum := sha256.Sum256(metaModelJSON)
	if got := hex.EncodeToString(sum[:]); got != metaModelSHA256 {
		t.Fatalf("metaModel.json sha256 = %s, want %s (pinned in main.go)", got, metaModelSHA256)
	}
}

// TestGenerateDeterministic proves the codegen invariant this migration
// depends on: identical input always produces byte-identical output, so
// `go generate` twice in a row is a clean `git diff`.
func TestGenerateDeterministic(t *testing.T) {
	first, err := Generate(metaModelJSON)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	second, err := Generate(metaModelJSON)
	if err != nil {
		t.Fatalf("Generate (second run): %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatalf("Generate is not deterministic: two runs on the same input produced different output")
	}
}

// TestGenerateContainsExpectedDeclarations is a coarse regression guard: if
// a future config.go edit accidentally drops an allowlisted type or field,
// or changes a Go type/tag pkg/lsp depends on, this fails loudly rather than
// surfacing only as a downstream compile error somewhere else in the
// package.
func TestGenerateContainsExpectedDeclarations(t *testing.T) {
	out, err := Generate(metaModelJSON)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	src := string(out)

	mustContain := []string{
		"// Code generated by cmd/lspgen",
		"DO NOT EDIT",
		"package lsp",
		"import \"encoding/json\"",

		"type DiagnosticSeverity int",
		"SeverityError       DiagnosticSeverity = 1",
		"type SymbolKind int",
		"SymbolKindFile          SymbolKind = 1",
		"SymbolKindTypeParameter SymbolKind = 26",
		"type SymbolTag int",
		"SymbolTagDeprecated SymbolTag = 1",
		"type FoldingRangeKind string",
		`FoldingRangeKindComment FoldingRangeKind = "comment"`,

		"type Position struct",
		"Line int `json:\"line\"`",
		"Character int `json:\"character\"`",
		"type Range struct",
		"Start Position `json:\"start\"`",
		"type Location struct",
		"URI DocumentURI `json:\"uri\"`",
		"type LocationLink struct",
		"type TextEdit struct",
		"NewText string `json:\"newText\"`",

		"type Diagnostic struct",
		"Code any `json:\"code,omitempty\"`",
		"Message string `json:\"message\"`",
		"RelatedInformation []DiagnosticRelatedInformation `json:\"relatedInformation,omitempty\"`",
		"type DiagnosticRelatedInformation struct",

		"type DocumentSymbol struct",
		"Children []DocumentSymbol `json:\"children,omitempty\"`",
		"type SymbolInformation struct",
		"ContainerName string `json:\"containerName,omitempty\"`",

		"type FoldingRange struct",
		"StartCharacter *int `json:\"startCharacter,omitempty\"`",
		"EndCharacter *int `json:\"endCharacter,omitempty\"`",

		"type MarkupContent struct",
		"Kind string `json:\"kind\"`",

		"type TextDocumentIdentifier struct",
		"type ReferenceContext struct",
		"type ReferenceParams struct",
		"type DefinitionParams struct",
		"type HoverParams struct",
		"type RenameParams struct",
		"NewName string `json:\"newName\"`",
		"type FoldingRangeParams struct",
		"type WorkspaceSymbolParams struct",
		"type DocumentSymbolParams struct",

		"type PublishDiagnosticsParams struct",
		"type ServerInfo struct",
		"type ClientInfo struct",
		"type TextDocumentItem struct",
		"LanguageID string `json:\"languageId\"`",
		"type VersionedTextDocumentIdentifier struct",
		"type DidOpenTextDocumentParams struct",
		"type DidChangeTextDocumentParams struct",
		"ContentChanges []TextDocumentContentChangeEvent `json:\"contentChanges\"`",
		"type InitializeResult struct",
		"Capabilities json.RawMessage `json:\"capabilities\"`",

		"type ClientCapabilities struct",
		"Workspace *WorkspaceClientCapabilities `json:\"workspace,omitempty\"`",
		"type WorkspaceClientCapabilities struct",
		"type WorkspaceEditClientCapabilities struct",
		"type TextDocumentClientCapabilities struct",
		"type DocumentSymbolClientCapabilities struct",
		"HierarchicalDocumentSymbolSupport bool `json:\"hierarchicalDocumentSymbolSupport,omitempty\"`",
		"type PublishDiagnosticsClientCapabilities struct",
	}
	for _, want := range mustContain {
		if !strings.Contains(src, want) {
			t.Errorf("generated output missing expected snippet: %q", want)
		}
	}

	// Excluded types must NOT be (re)declared here — they stay hand-written.
	mustNotContain := []string{
		"type WorkspaceEdit struct",
		"type TextDocumentEdit struct",
		"type OptionalVersionedTextDocumentIdentifier struct",
		"type Hover struct",
		"type TextDocumentContentChangeEvent struct",
		"type DocumentSymbolResult struct",
		"type InitializeParams struct",
	}
	for _, notWant := range mustNotContain {
		if strings.Contains(src, notWant) {
			t.Errorf("generated output unexpectedly declares excluded type: %q", notWant)
		}
	}
}

// TestResolveTypeRejectsUnsupportedKinds locks in the fail-loud contract: a
// type kind this generator has no rule for (or an unregistered reference)
// must error, never silently fall back to a guess.
func TestResolveTypeRejectsUnsupportedKinds(t *testing.T) {
	noNames := map[string]bool{}
	noExternal := map[string]string{}

	t.Run("unsupported kind", func(t *testing.T) {
		_, _, err := resolveType(anyType{Kind: "or"}, noNames, noNames, noExternal)
		if err == nil {
			t.Fatal("resolveType(or) = nil error, want error")
		}
	})
	t.Run("unresolved reference", func(t *testing.T) {
		_, _, err := resolveType(anyType{Kind: "reference", Name: "SomeUnregisteredType"}, noNames, noNames, noExternal)
		if err == nil {
			t.Fatal("resolveType(reference to unregistered type) = nil error, want error")
		}
	})
	t.Run("unsupported base", func(t *testing.T) {
		_, _, err := resolveType(anyType{Kind: "base", Name: "RegExp"}, noNames, noNames, noExternal)
		if err == nil {
			t.Fatal("resolveType(base RegExp) = nil error, want error")
		}
	})
	t.Run("array missing element", func(t *testing.T) {
		_, _, err := resolveType(anyType{Kind: "array"}, noNames, noNames, noExternal)
		if err == nil {
			t.Fatal("resolveType(array, no element) = nil error, want error")
		}
	})
}

// TestBuildStructOnlyFieldsRejectsUnknownName ensures a typo in a
// structConfig.onlyFields entry fails generation instead of silently
// dropping a field.
func TestBuildStructOnlyFieldsRejectsUnknownName(t *testing.T) {
	var mm metaModel
	if err := json.Unmarshal(metaModelJSON, &mm); err != nil {
		t.Fatalf("unmarshal metaModel.json: %v", err)
	}
	bn := newByName(&mm)

	cfg := structConfig{name: "Position", onlyFields: []string{"line", "notAnActualProperty"}}
	_, _, err := buildStruct(cfg, bn, map[string]bool{}, map[string]bool{}, map[string]string{})
	if err == nil {
		t.Fatal("buildStruct with a bogus onlyFields entry = nil error, want error")
	}
}
