// Code generated by cmd/lspgen from the pinned LSP 3.18.0 metaModel.json; DO NOT EDIT.
//
// Regenerate:    go generate ./pkg/lsp/...
// Source:        https://raw.githubusercontent.com/microsoft/language-server-protocol/gh-pages/_specifications/lsp/3.18.0/metaModel/metaModel.json
// Pinned copy:   cmd/lspgen/metaModel.json (sha256 caae8df639a4248520a3f589fd72945365e9d8ebca5baf564161a515430d9d41)
// Allowlist:     cmd/lspgen/config.go (also documents every excluded/hand-written type)

package lsp

import "encoding/json"

// DiagnosticSeverity is the LSP severity enumeration.
type DiagnosticSeverity int

// LSP diagnostic severities.
const (
	SeverityError       DiagnosticSeverity = 1
	SeverityWarning     DiagnosticSeverity = 2
	SeverityInformation DiagnosticSeverity = 3
	SeverityHint        DiagnosticSeverity = 4
)

// SymbolKind is the LSP symbol-kind enumeration (1..26).
type SymbolKind int

// LSP symbol kinds.
const (
	SymbolKindFile          SymbolKind = 1
	SymbolKindModule        SymbolKind = 2
	SymbolKindNamespace     SymbolKind = 3
	SymbolKindPackage       SymbolKind = 4
	SymbolKindClass         SymbolKind = 5
	SymbolKindMethod        SymbolKind = 6
	SymbolKindProperty      SymbolKind = 7
	SymbolKindField         SymbolKind = 8
	SymbolKindConstructor   SymbolKind = 9
	SymbolKindEnum          SymbolKind = 10
	SymbolKindInterface     SymbolKind = 11
	SymbolKindFunction      SymbolKind = 12
	SymbolKindVariable      SymbolKind = 13
	SymbolKindConstant      SymbolKind = 14
	SymbolKindString        SymbolKind = 15
	SymbolKindNumber        SymbolKind = 16
	SymbolKindBoolean       SymbolKind = 17
	SymbolKindArray         SymbolKind = 18
	SymbolKindObject        SymbolKind = 19
	SymbolKindKey           SymbolKind = 20
	SymbolKindNull          SymbolKind = 21
	SymbolKindEnumMember    SymbolKind = 22
	SymbolKindStruct        SymbolKind = 23
	SymbolKindEvent         SymbolKind = 24
	SymbolKindOperator      SymbolKind = 25
	SymbolKindTypeParameter SymbolKind = 26
)

// SymbolTag is the LSP symbol-tag enumeration.
type SymbolTag int

// LSP symbol tags.
const (
	SymbolTagDeprecated SymbolTag = 1
)

// FoldingRangeKind categorizes a FoldingRange (e.g. so a client's "fold
// all comments" command can select just that kind). Per the LSP spec it is
// an open string enumeration — the values below are the standardized ones
// (LSP metaModel, FoldingRangeKind), but a server may report others.
type FoldingRangeKind string

// Standardized folding range kinds.
const (
	FoldingRangeKindComment FoldingRangeKind = "comment"
	FoldingRangeKindImports FoldingRangeKind = "imports"
	FoldingRangeKindRegion  FoldingRangeKind = "region"
)

// Position is a zero-based line/character offset. Per the LSP spec character
// offsets are UTF-16 code units by default; callers that map to the structast
// DTO (1-indexed, UTF-8) convert at the boundary.
type Position struct {
	// Line is the LSP metaModel "line" property of Position.
	Line int `json:"line"`

	// Character is the LSP metaModel "character" property of Position.
	Character int `json:"character"`
}

// Range is a [Start, End) span within a document.
type Range struct {
	// Start is the LSP metaModel "start" property of Range.
	Start Position `json:"start"`

	// End is the LSP metaModel "end" property of Range.
	End Position `json:"end"`
}

// Location is a range within a specific document.
type Location struct {
	// URI is the LSP metaModel "uri" property of Location.
	URI DocumentURI `json:"uri"`

	// Range is the LSP metaModel "range" property of Location.
	Range Range `json:"range"`
}

// LocationLink is a definition/declaration result element that additionally
// carries the origin span the link was resolved from. lspbridge's Definition
// method does not advertise linkSupport (see reads.go) so servers never send
// this today; it is generated now as near-term surface for a client that does.
type LocationLink struct {
	// OriginSelectionRange, if present, is the span in the source document the link was resolved from.
	OriginSelectionRange *Range `json:"originSelectionRange,omitempty"`

	// TargetURI is the document the link points to.
	TargetURI DocumentURI `json:"targetUri"`

	// TargetRange is the full range of the target element (e.g. a whole function body).
	TargetRange Range `json:"targetRange"`

	// TargetSelectionRange is the narrower span to actually select/highlight (e.g. just the function name); always contained within TargetRange.
	TargetSelectionRange Range `json:"targetSelectionRange"`
}

// TextEdit replaces Range with NewText.
type TextEdit struct {
	// Range is the LSP metaModel "range" property of TextEdit.
	Range Range `json:"range"`

	// NewText is the LSP metaModel "newText" property of TextEdit.
	NewText string `json:"newText"`
}

// Diagnostic is a problem reported at a range.
type Diagnostic struct {
	// Range is the LSP metaModel "range" property of Diagnostic.
	Range Range `json:"range"`

	// Severity is the LSP metaModel "severity" property of Diagnostic.
	Severity DiagnosticSeverity `json:"severity,omitempty"`

	// Code is any because the LSP spec allows either an integer or a string code.
	Code any `json:"code,omitempty"`

	// Source is the LSP metaModel "source" property of Diagnostic.
	Source string `json:"source,omitempty"`

	// Message stays string: LSP 3.18 widened this to string | MarkupContent behind the textDocument.diagnostic.markupMessageSupport client capability, which lspbridge does not advertise, so only the string arm is ever populated on the wire in practice.
	Message string `json:"message"`

	// RelatedInformation lists related diagnostic locations, e.g. when symbol-names within a scope collide all definitions can be marked via this property (LSP metaModel: Diagnostic.relatedInformation).
	RelatedInformation []DiagnosticRelatedInformation `json:"relatedInformation,omitempty"`
}

// DiagnosticRelatedInformation points at another location related to a
// Diagnostic (e.g. another definition site involved in a name collision).
type DiagnosticRelatedInformation struct {
	// Location is the LSP metaModel "location" property of DiagnosticRelatedInformation.
	Location Location `json:"location"`

	// Message is the LSP metaModel "message" property of DiagnosticRelatedInformation.
	Message string `json:"message"`
}

// DocumentSymbol is the modern, hierarchical result element of
// textDocument/documentSymbol: a symbol with a nesting Range, a narrower
// SelectionRange (the name), and nested Children. A server returns this shape
// only when the client advertises hierarchicalDocumentSymbolSupport; otherwise
// it returns the flat [SymbolInformation] form.
type DocumentSymbol struct {
	// Name is the LSP metaModel "name" property of DocumentSymbol.
	Name string `json:"name"`

	// Detail is the LSP metaModel "detail" property of DocumentSymbol.
	Detail string `json:"detail,omitempty"`

	// Kind is the LSP metaModel "kind" property of DocumentSymbol.
	Kind SymbolKind `json:"kind"`

	// Tags is the LSP metaModel "tags" property of DocumentSymbol.
	Tags []SymbolTag `json:"tags,omitempty"`

	// Deprecated is the LSP metaModel "deprecated" property of DocumentSymbol.
	Deprecated bool `json:"deprecated,omitempty"`

	// Range is the LSP metaModel "range" property of DocumentSymbol.
	Range Range `json:"range"`

	// SelectionRange is the LSP metaModel "selectionRange" property of DocumentSymbol.
	SelectionRange Range `json:"selectionRange"`

	// Children is the LSP metaModel "children" property of DocumentSymbol.
	Children []DocumentSymbol `json:"children,omitempty"`
}

// SymbolInformation is the legacy, flat result element of
// textDocument/documentSymbol (and the workspace/symbol result): a symbol with
// a full [Location] rather than nested ranges. ContainerName is the enclosing
// symbol's name, if any.
type SymbolInformation struct {
	// Name is the LSP metaModel "name" property of SymbolInformation.
	Name string `json:"name"`

	// Kind is the LSP metaModel "kind" property of SymbolInformation.
	Kind SymbolKind `json:"kind"`

	// Tags is the LSP metaModel "tags" property of SymbolInformation.
	Tags []SymbolTag `json:"tags,omitempty"`

	// Deprecated is the LSP metaModel "deprecated" property of SymbolInformation.
	Deprecated bool `json:"deprecated,omitempty"`

	// Location is the LSP metaModel "location" property of SymbolInformation.
	Location Location `json:"location"`

	// ContainerName is the LSP metaModel "containerName" property of SymbolInformation.
	ContainerName string `json:"containerName,omitempty"`
}

// PublishDiagnosticsParams is the payload of the server-to-client
// textDocument/publishDiagnostics notification.
type PublishDiagnosticsParams struct {
	// URI is the LSP metaModel "uri" property of PublishDiagnosticsParams.
	URI DocumentURI `json:"uri"`

	// Version is the LSP metaModel "version" property of PublishDiagnosticsParams.
	Version int `json:"version,omitempty"`

	// Diagnostics is the LSP metaModel "diagnostics" property of PublishDiagnosticsParams.
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// FoldingRange is one foldable line span. StartCharacter/EndCharacter are
// pointers because the LSP spec gives the unset case its own meaning
// ("defaults to the length of the start/end line") distinct from character 0;
// a server that folds whole lines (as org-lsp does) leaves both nil.
type FoldingRange struct {
	// StartLine is the LSP metaModel "startLine" property of FoldingRange.
	StartLine int `json:"startLine"`

	// Pointer (not a plain optional int): the LSP spec gives "unset" its own meaning ("defaults to the length of the start line") distinct from character 0, which int+omitempty cannot represent.
	StartCharacter *int `json:"startCharacter,omitempty"`

	// EndLine is the LSP metaModel "endLine" property of FoldingRange.
	EndLine int `json:"endLine"`

	// Pointer (not a plain optional int): the LSP spec gives "unset" its own meaning ("defaults to the length of the end line") distinct from character 0, which int+omitempty cannot represent.
	EndCharacter *int `json:"endCharacter,omitempty"`

	// Kind is the LSP metaModel "kind" property of FoldingRange.
	Kind FoldingRangeKind `json:"kind,omitempty"`

	// CollapsedText is the LSP metaModel "collapsedText" property of FoldingRange.
	CollapsedText string `json:"collapsedText,omitempty"`
}

// MarkupContent is rendered hover/documentation content. Kind is "plaintext"
// or "markdown".
type MarkupContent struct {
	// Kind stays string rather than the MarkupKind enum: pkg/lsp's decodeMarkup/decodeMarkupObject helpers (reads.go) build it from literal string constants, and existing tests compare it directly against string locals.
	Kind string `json:"kind"`

	// Value is the LSP metaModel "value" property of MarkupContent.
	Value string `json:"value"`
}

// TextDocumentIdentifier names a document by URI.
type TextDocumentIdentifier struct {
	// URI is the LSP metaModel "uri" property of TextDocumentIdentifier.
	URI DocumentURI `json:"uri"`
}

// ReferenceContext scopes a references request; IncludeDeclaration adds the
// symbol's own declaration to the returned locations.
type ReferenceContext struct {
	// IncludeDeclaration is the LSP metaModel "includeDeclaration" property of ReferenceContext.
	IncludeDeclaration bool `json:"includeDeclaration"`
}

// ReferenceParams is the textDocument/references request payload. Position is
// 0-indexed with a UTF-16 character offset.
type ReferenceParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of ReferenceParams.
	TextDocument TextDocumentIdentifier `json:"textDocument"`

	// Position is the LSP metaModel "position" property of ReferenceParams.
	Position Position `json:"position"`

	// Context is the LSP metaModel "context" property of ReferenceParams.
	Context ReferenceContext `json:"context"`
}

// DefinitionParams is the textDocument/definition request payload. Position is
// 0-indexed with a UTF-16 character offset.
type DefinitionParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of DefinitionParams.
	TextDocument TextDocumentIdentifier `json:"textDocument"`

	// Position is the LSP metaModel "position" property of DefinitionParams.
	Position Position `json:"position"`
}

// HoverParams is the textDocument/hover request payload. Position is 0-indexed
// with a UTF-16 character offset.
type HoverParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of HoverParams.
	TextDocument TextDocumentIdentifier `json:"textDocument"`

	// Position is the LSP metaModel "position" property of HoverParams.
	Position Position `json:"position"`
}

// RenameParams is the textDocument/rename request payload: rename the symbol at
// Position (0-indexed, UTF-16) to NewName. The server computes the edit purely
// and returns a [WorkspaceEdit]; it never writes to disk.
type RenameParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of RenameParams.
	TextDocument TextDocumentIdentifier `json:"textDocument"`

	// Position is the LSP metaModel "position" property of RenameParams.
	Position Position `json:"position"`

	// NewName is the LSP metaModel "newName" property of RenameParams.
	NewName string `json:"newName"`
}

// FoldingRangeParams is the textDocument/foldingRange request payload.
type FoldingRangeParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of FoldingRangeParams.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// WorkspaceSymbolParams is the workspace/symbol request payload. Per the LSP
// spec, Query should be matched "in a relaxed way" (case-insensitive,
// characters appearing in order); an empty Query requests every symbol.
type WorkspaceSymbolParams struct {
	// Query is the LSP metaModel "query" property of WorkspaceSymbolParams.
	Query string `json:"query"`
}

// DocumentSymbolParams is the textDocument/documentSymbol request payload.
type DocumentSymbolParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of DocumentSymbolParams.
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

// ServerInfo identifies the server.
type ServerInfo struct {
	// Name is the LSP metaModel "name" property of ServerInfo.
	Name string `json:"name"`

	// Version is the LSP metaModel "version" property of ServerInfo.
	Version string `json:"version,omitempty"`
}

// ClientInfo identifies the client to the server.
type ClientInfo struct {
	// Name is the LSP metaModel "name" property of ClientInfo.
	Name string `json:"name"`

	// Version is the LSP metaModel "version" property of ClientInfo.
	Version string `json:"version,omitempty"`
}

// TextDocumentItem is a document opened on the server.
type TextDocumentItem struct {
	// URI is the LSP metaModel "uri" property of TextDocumentItem.
	URI DocumentURI `json:"uri"`

	// LanguageID stays string rather than the LanguageKind enum: it's an open enumeration (supportsCustomValues) and every existing call site (pyright.go, broker.go, tests) passes/receives a plain string local.
	LanguageID string `json:"languageId"`

	// Version is the LSP metaModel "version" property of TextDocumentItem.
	Version int `json:"version"`

	// Text is the LSP metaModel "text" property of TextDocumentItem.
	Text string `json:"text"`
}

// VersionedTextDocumentIdentifier identifies a document at a version.
type VersionedTextDocumentIdentifier struct {
	// URI is the LSP metaModel "uri" property of VersionedTextDocumentIdentifier.
	URI DocumentURI `json:"uri"`

	// Version is the LSP metaModel "version" property of VersionedTextDocumentIdentifier.
	Version int `json:"version"`
}

// DidOpenTextDocumentParams is the textDocument/didOpen payload.
type DidOpenTextDocumentParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of DidOpenTextDocumentParams.
	TextDocument TextDocumentItem `json:"textDocument"`
}

// DidChangeTextDocumentParams is the textDocument/didChange payload.
type DidChangeTextDocumentParams struct {
	// TextDocument is the LSP metaModel "textDocument" property of DidChangeTextDocumentParams.
	TextDocument VersionedTextDocumentIdentifier `json:"textDocument"`

	// ContentChanges is the LSP metaModel "contentChanges" property of DidChangeTextDocumentParams.
	ContentChanges []TextDocumentContentChangeEvent `json:"contentChanges"`
}

// InitializeResult is the server's initialize response. The raw capabilities
// object is retained verbatim so per-server feature detection can inspect it
// without this package modeling the whole surface.
type InitializeResult struct {
	// Capabilities stays raw JSON: ServerCapabilities is by far the largest structure in the whole metaModel and modeling it is not needed for per-server feature detection, which reads this raw object directly.
	Capabilities json.RawMessage `json:"capabilities"`

	// ServerInfo is the LSP metaModel "serverInfo" property of InitializeResult.
	ServerInfo *ServerInfo `json:"serverInfo,omitempty"`
}

// ClientCapabilities is the advertised client capability set. Kept minimal
// and honest for P0; grown as concrete features (rename, references,
// diagnostics pull) are added.
type ClientCapabilities struct {
	// Workspace is the LSP metaModel "workspace" property of ClientCapabilities.
	Workspace *WorkspaceClientCapabilities `json:"workspace,omitempty"`

	// TextDocument is the LSP metaModel "textDocument" property of ClientCapabilities.
	TextDocument *TextDocumentClientCapabilities `json:"textDocument,omitempty"`
}

// WorkspaceClientCapabilities is the workspace-scoped capability subset.
type WorkspaceClientCapabilities struct {
	// WorkspaceEdit is the LSP metaModel "workspaceEdit" property of WorkspaceClientCapabilities.
	WorkspaceEdit *WorkspaceEditClientCapabilities `json:"workspaceEdit,omitempty"`
}

// WorkspaceEditClientCapabilities advertises WorkspaceEdit support.
type WorkspaceEditClientCapabilities struct {
	// DocumentChanges is the LSP metaModel "documentChanges" property of WorkspaceEditClientCapabilities.
	DocumentChanges bool `json:"documentChanges,omitempty"`
}

// TextDocumentClientCapabilities is the document-scoped capability subset.
type TextDocumentClientCapabilities struct {
	// PublishDiagnostics advertises support for the server-to-client
	// textDocument/publishDiagnostics notification. Per-feature capability
	// structs continue to land here as they're wired in.
	PublishDiagnostics *PublishDiagnosticsClientCapabilities `json:"publishDiagnostics,omitempty"`

	// DocumentSymbol advertises textDocument/documentSymbol support; its
	// HierarchicalDocumentSymbolSupport flag selects the nested DocumentSymbol
	// result shape over the flat SymbolInformation one.
	DocumentSymbol *DocumentSymbolClientCapabilities `json:"documentSymbol,omitempty"`
}

// DocumentSymbolClientCapabilities advertises the client's
// textDocument/documentSymbol support.
type DocumentSymbolClientCapabilities struct {
	// HierarchicalDocumentSymbolSupport asks the server to return the nested
	// [DocumentSymbol] tree rather than a flat [SymbolInformation] list.
	HierarchicalDocumentSymbolSupport bool `json:"hierarchicalDocumentSymbolSupport,omitempty"`
}

// PublishDiagnosticsClientCapabilities advertises the client's
// textDocument/publishDiagnostics support.
type PublishDiagnosticsClientCapabilities struct {
	// RelatedInformation is the LSP metaModel "relatedInformation" property of PublishDiagnosticsClientCapabilities.
	RelatedInformation bool `json:"relatedInformation,omitempty"`
}
